name: Build Windows Executable with PyInstaller

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows 10
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller main.py --onefile --name=Operata

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: operata-windows-exe
          path: dist/Operata.exe

